version: '3.7'
services:
  mongo_db:
    image: mongo:4.2.3
    container_name: mongodb_container
    restart: always
    ports:
      - "2717:27017"
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    image: book_api
    container_name: book_api
    restart: always
    ports:
      - 4000:3000
    volumes:
      - .:/usr/src/app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo_db:27017/book_db
      - DB_NAME=book_db
      - COLLECTION_NAME=books
      - NAME:AmitDas
    depends_on:
      - mongo_db
volumes:
  mongo_db: {}
